# Generated by Django 5.2.8 on 2025-11-14 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.TimeField()),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'ordering': ['tipo_item'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DiscoMp3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.TimeField()),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discos_mp3', to='core.item')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CorreoProveedor',
            fields=[
                ('correo', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoProveedor',
            fields=[
                ('telefono', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('telefono', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='core.usuario')),
            ],
            options={
                'ordering': ['telefono'],
            },
        ),
        migrations.CreateModel(
            name='Recopilacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('publica', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recopilaciones', to='core.usuario')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('medio_pago', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.usuario')),
            ],
            options={
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('correo', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='core.usuario')),
            ],
            options={
                'ordering': ['correo'],
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='core.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='core.usuario')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vinilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('anio_salida', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinilos', to='core.cancion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinilos', to='core.item')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinilos', to='core.proveedor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DiscoMp3Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cancion')),
                ('disco_mp3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discomp3')),
            ],
            options={
                'unique_together': {('disco_mp3', 'cancion')},
            },
        ),
        migrations.CreateModel(
            name='RecopilacionCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cancion')),
                ('recopilacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recopilacion')),
            ],
            options={
                'unique_together': {('recopilacion', 'cancion')},
            },
        ),
        migrations.CreateModel(
            name='ViniloCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cancion')),
                ('vinilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vinilo')),
            ],
            options={
                'unique_together': {('vinilo', 'cancion')},
            },
        ),
    ]
