# Generated by Django 5.2.8 on 2025-11-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinilo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='item',
        ),
        migrations.RemoveField(
            model_name='discomp3',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='correo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recopilacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={},
        ),
        migrations.AlterModelOptions(
            name='valoracion',
            options={},
        ),
        migrations.RemoveField(
            model_name='vinilo',
            name='cancion',
        ),
        migrations.AddField(
            model_name='discomp3',
            name='inventario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_estimado_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.discomp3'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacion_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_recibidos', to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vinilo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.vinilo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contrasena',
            field=models.CharField(default='temporal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinilo',
            name='inventario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado por proveedor'), ('rechazado', 'Rechazado por proveedor'), ('enviado', 'Enviado'), ('recibido', 'Recibido')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.usuario'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
