# Generated by Django 5.2.8 on 2025-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vinilo_item_remove_pedido_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correo',
            options={'ordering': ['correo']},
        ),
        migrations.AlterModelOptions(
            name='correoproveedor',
            options={'ordering': ['correo']},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'ordering': ['telefono']},
        ),
        migrations.AlterModelOptions(
            name='telefonoproveedor',
            options={'ordering': ['telefono']},
        ),
        migrations.AddField(
            model_name='correo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='correoproveedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='telefonoproveedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='correo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='correoproveedor',
            name='correo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='telefonoproveedor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='correo',
            unique_together={('usuario', 'correo')},
        ),
        migrations.AlterUniqueTogether(
            name='correoproveedor',
            unique_together={('proveedor', 'correo')},
        ),
        migrations.AlterUniqueTogether(
            name='telefono',
            unique_together={('usuario', 'telefono')},
        ),
        migrations.AlterUniqueTogether(
            name='telefonoproveedor',
            unique_together={('proveedor', 'telefono')},
        ),
    ]
